// Source text for content/celebrations.json (V5_DESIGN section 16). Run: node tools/content_src/build_content.js
// Plain strings; slots: {other} (the person talked to), {name} (the honoured person), {a} {b} (people in a scene),
// {place} (the venue), {reason}. No line is explicit; no line is about or with a child.
module.exports = {
  joke: [
    "I asked the AI for a joke. It sent me a subscription offer.",
    "Why did the technician cross the airlock? To get to the other side. It took forty minutes.",
    "My suit and I have an agreement. It does not leak, I do not complain.",
    "I told the rover to go slow. It said, that is my only speed.",
    "They called it a smart habitat. It still cannot find my left sock.",
    "Our greenhouse produced a tomato the size of my head. I named it Gerald.",
    "The ration bar tastes like cardboard with ambitions.",
    "I would tell you a joke about vacuum, but it is empty.",
    "My blood type is coffee positive.",
    "Somebody left a spreadsheet in the airlock. It was cycled out. Best outcome in months.",
    "The AI says it learns from us. That explains the mood swings.",
    "I dreamt in pie charts last night. Quarterly pie charts. I woke up screaming.",
    "My boss said we are a family. Then he scheduled me for a double shift. Classic family.",
    "I like our dust storms. They keep the visitors out.",
    "The recycler made me a lovely tea. I choose not to ask what it was yesterday.",
    "I put the kettle on and the whole base lost power. I stand by the kettle.",
    "A hydroponics joke: it never gets old. It just grows on you.",
    "Did you hear the commander tried to fix the vending machine? The vending machine won.",
    "I asked for a window office. They gave me a window. In the corridor. Facing a wall.",
    "I have been on this colony for months and I still cannot pronounce the water recycler.",
    "They said there would be gravity on this planet. They did not say how much.",
    "My shift ended at six. My to-do list did not get the message.",
    "The best thing about the airlock is the two minutes of peace between doors.",
    "The AI-powered toaster has opinions. I do not like them.",
    "Someone ate my labelled yoghurt. It was labelled in Latin. Still no excuse."
  ],
  rivalry: [
    "Oh, you are working today, {other}? What an unusual change of pace.",
    "I saw your report, {other}. Bold choice, formatting it like a ransom note.",
    "Some of us have actual deadlines, {other}.",
    "Funny, I do not remember anyone asking your opinion. I have checked the minutes.",
    "Nice of you to join us, {other}. We started the shift four hours ago.",
    "I am not saying I am better than you, {other}. The ledger is.",
    "I would help you with that, {other}, but I would hate to steal your learning moment.",
    "Interesting theory, {other}. Shall we try it? On you?",
    "Your mug says World's Best Colleague. I checked. It is a lie.",
    "Congratulations on the promotion, {other}. Truly. I am only a little bit sick.",
    "{other}, I am going to need you to stop breathing so loudly in my airlock.",
    "I saw what you did with the budget, {other}. Pure art. I mean, a horror painting.",
    "Of course you got the extra ration. You always know the right person to flatter.",
    "I will let your mistake slide, {other}. This time. And the three times before.",
    "{other}, I am just curious. Is it hard being wrong so confidently?",
    "Do not worry, {other}, nobody expects much from you. It is a very low bar. You still tripped on it.",
    "You are dripping on my clean floor, {other}. I would say it is a metaphor. But it is just water.",
    "Race you to the next promotion, {other}. I will wait for you at the top. With a sandwich."
  ],
  awkward: [
    "Oh. Um. That is very kind. I have a thing. Somewhere else. Right now.",
    "I am flattered, {other}. I am also, um, going to look at that wall for a bit.",
    "That is sweet, {other}, but I think we should keep it professional. Very professional.",
    "I... did not realise. Sorry. I need to check my pocket for something. Anything.",
    "Right. Okay. I will just pretend I did not hear that. Deal?",
    "{other}, you are great. Really. Please stop saying things now.",
    "I think the air is thin in here. I need to leave. For air.",
    "Thanks. I am, um, seeing someone. Their name is Paperwork.",
    "Oh dear. I am the wrong person for that, {other}. I would love to stay friends. If you still want.",
    "I do not know what to say. So I will say: nice weather. In the dome. Under the lamps.",
    "That landed badly. I can feel the room cooling. We should both leave.",
    "I appreciate the effort, {other}. I will treasure it. Quietly. Alone. Far away.",
    "Is there a pause button for this conversation? Asking for me.",
    "Um. {other}. I think you meant someone else. Someone with different plans.",
    "Okay, that was a lot. I am going to go and not think about that. Starting now.",
    "{other}, I am committed. To my work. To my houseplant. Not to that.",
    "I am going to pretend my radio just rang. Beep beep. Sorry, must go.",
    "You are brave, {other}. I am a coward. I am leaving.",
    "Ha ha. Good one. That was a joke, right? Please say joke.",
    "{other}, I think we both need a very long cup of tea. Separately."
  ],
  decline: [
    "That is very sweet, {other}. I will take it as a compliment and nothing else.",
    "Thank you, {other}. I do not think it would work. But you are a good friend.",
    "I am flattered. I am also taken. Or not interested. Both, really.",
    "Nice try, {other}. A for effort.",
    "I am going to leave before this gets worse for either of us.",
    "Kind of you, {other}. No. But kind."
  ],
  flirt_reply: [
    "You are too much, {other}. Please keep going.",
    "Ha! You are trouble. I like trouble.",
    "Careful, {other}. I might say yes.",
    "Stop it. No, do not stop it.",
    "I am blushing. I hope the lamp hides it.",
    "You say the nicest things. Say more.",
    "I was hoping you would say that.",
    "Is that right? Tell me again, slower.",
    "You are the best part of my day, {other}.",
    "I should be working. I would rather be here."
  ],
  innuendo_reply: [
    "{other}! You cannot say that in the corridor. Say it again in my quarters.",
    "Is that what they teach in orientation now? I should have paid more attention.",
    "You are outrageous, {other}. Do not ever change.",
    "I will pretend I did not hear that. I heard it. I am pretending badly.",
    "That was either a fantastic line or a medical symptom. I am happy either way.",
    "Keep talking like that and the AI will flag us for wellbeing.",
    "I like the way you think. The way it goes sideways.",
    "I accept. Whatever it was. I accept.",
    "If I blush, blame the humidity.",
    "You are a menace. Please stay a menace.",
    "Bold. I like bold. Say it again when nobody is listening.",
    "My ears are burning. My cheeks too. This is a very good feeling."
  ],
  party_talk: [
    "Great music! Who picked it? Whoever it was, a raise for them.",
    "I have not danced in months. My knees have opinions.",
    "Did you try the dip? It is the green thing. It is the only thing.",
    "{other}, you have a lovely dress. I did not know the colony had dresses.",
    "I am only here for the snacks. And the company. Mostly the snacks.",
    "This is the first time I have not talked about work all day. Do not remind me.",
    "Who is DJ? Is it the AI? It has played the same song four times.",
    "Cheers, {other}. To getting out of that suit for one night.",
    "A party! In this economy! Brilliant.",
    "I love how the lights go. I could dance all night. I will dance until the lights flicker.",
    "I like seeing everybody out of uniform. We look like humans.",
    "Hold my drink. I have a move.",
    "Have you met the guest of honour? They are lovely. They are also hiding.",
    "I am here to make memories. Or at least blurry photos.",
    "I will have one more drink and then I will leave. Famous last words.",
    "Is the floor supposed to be sticky? It adds character.",
    "The best parties happen when the shift ends. This one just started.",
    "I came for the cake. Where is the cake?",
    "Thank you for inviting me. I almost stayed in to do laundry.",
    "I think the dome is great for parties. You can see the stars while you embarrass yourself.",
    "Somebody should start a dance-off. I will not. But somebody should.",
    "I will go and talk to that person by the wall. Wish me luck.",
    "The punch is a mystery. I recommend it.",
    "I have a theory the AI is hosting this party. It keeps asking for feedback.",
    "Free snacks are the best snacks.",
    "We should do this every week. Not every week. Every month. Every week is too many hangovers.",
    "Everyone I like is in the same room. This is the dream.",
    "I am going to dance badly and not care. Join me.",
    "It is nice to see the commander smile. It looks painful, but nice.",
    "Is it true the dome club has a robot DJ? I want one for my birthday."
  ],
  toast: [
    "To {name}! May the oxygen never run out and the coffee never run dry.",
    "A toast to {name}: the best thing about this base, after the airlocks.",
    "To {name}! Another year, another airlock cycle survived.",
    "Raise your glasses for {name}. They make the colony brighter.",
    "To {name}, who keeps us sane. Mostly.",
    "To {name}! We would be lost without you. Probably literally.",
    "Cheers to {name}. May your luck be like a fresh seal: tight and reliable.",
    "To {name}, the heart of this place. A heart with excellent pressure.",
    "Let us drink to {name}. Because we can. Because we deserve it.",
    "To {name}! Long may you reign over the canteen schedule.",
    "To friends, to family, and to {name}, who is a bit of both.",
    "To {name}: proof that good things survive in bad environments.",
    "Here is to {name}. May your days be long and your shifts be short.",
    "To {name}! You made it. We are all very proud. And a little tipsy.",
    "To {name}, our favourite person. Do not tell the others.",
    "A toast to the occasion: {reason}. Nobody deserves it more than {name}.",
    "Friends, colleagues, strangers who got free snacks: to {name}!",
    "To {name}. I have a speech. It is one word. Cheers!",
    "Glasses up. To {name}. May they never have to attend another budget meeting.",
    "To {name}! And to the AI which, for once, did not ruin the evening."
  ],
  sing: [
    "Oh, the air is thin and the pay is low, but my heart is full, so off we go!",
    "I will always love you, little greenhouse, even if you give me blight!",
    "Take me home, rover road, to the place where the oxygen is mine!",
    "Row, row, row your rover, gently down the crater!",
    "Twinkle, twinkle, little base, how I wonder what is for lunch!"
  ],
  offers: {
    birthday: ["It is {name}'s birthday. Throw a party?", "{name} has a birthday today. A party would mean a lot."],
    promotion: ["{name} has been promoted. Throw a party?", "A promotion for {name}! The crew would like to celebrate."],
    goal: ["The colony reached a goal: {reason}. Throw a party?", "A goal is done: {reason}. People want to celebrate."],
    medal: ["{name} earned a medal. Throw a party?", "A medal for {name}. A party would suit."],
    structure: ["The {reason} is finished. Throw a party to open it?", "The {reason} is open. Celebrate?"],
    wedding: ["{name} and the new spouse just got married. Throw a wedding party?", "A wedding! Throw a party?"],
    adoption: ["{name} adopted a child. Throw a welcome party?", "A new family member. Throw a welcome party?"],
    record: ["{name} set a record on the arcade. Throw a party?", "A record from {name}! Celebrate?"]
  },
  auto_small: [
    "Nobody threw a party, so people gathered by themselves for {reason}.",
    "A few friends of {name} met in the {place} anyway."
  ],
  drama_small: [
    { id: "spill", text: "{a} spilled a drink on {b}. Everybody laughed. {b} laughed a little less." },
    { id: "spill2", text: "{a} knocked over the snack table. The dip is a total loss." },
    { id: "awkward_flirt", text: "{a} flirted with {b} in front of everyone. {b} looked for the exit." },
    { id: "bad_joke", text: "{a} told a bad joke. The silence was impressive." },
    { id: "dance_off", text: "{a} and {b} started a dance-off. The crowd voted for chaos." },
    { id: "tipsy_song", text: "{a} got tipsy and sang. Several people clapped. Several people left." },
    { id: "ex_arrives", text: "{a}'s ex arrived. The room went quiet. Then the music went on." },
    { id: "speech", text: "{a} gave a toast that lasted twelve minutes. People checked the clock." },
    { id: "wrong_name", text: "{a} called {b} by the wrong name. Twice." },
    { id: "ate_cake", text: "{a} ate the whole cake before the toast. The honoured person did not mind. Mostly." },
    { id: "karaoke", text: "{a} took the microphone and would not give it back." },
    { id: "lost_shoe", text: "{a} lost a shoe in the dome. Nobody could explain it." },
    { id: "photo", text: "{a} took a photo with the whole room. {b} blinked in all of them." },
    { id: "trip", text: "{a} tripped on the dance floor and called it a new dance." },
    { id: "gossip", text: "{a} told {b} a secret. The whole room now knows." },
    { id: "bad_cook", text: "{a} brought a homemade dish. Nobody asked what was in it." },
    { id: "slow_dance", text: "{a} asked {b} for a slow dance. The answer was yes. The room went aww." },
    { id: "ai_speech", text: "The base AI offered a congratulations speech. It said the wrong name." },
    { id: "hiccup", text: "{a} got the hiccups during the toast. They lasted all night." },
    { id: "stuck", text: "{a} got stuck in a very small chair. It took three people." }
  ],
  drama_big: {
    breakup: [
      "{a} ended things with {b} in front of everyone. The music stopped. Then it started again, softer.",
      "{a} and {b} broke up at the party. Loudly. With an audience."
    ],
    jealous: [
      "{a} saw {b} dancing with someone else and made a scene. Three people tried to calm {a} down.",
      "A jealous scene: {a} threw a drink at the wall near {b}. Near. The wall was fine."
    ],
    affair: [
      "A secret came out at the party: {a} had been seeing someone else. {b} heard everything.",
      "{a} and an unexpected guest were seen together. {b} was not amused."
    ],
    proposal: [
      "{a} proposed to {b} in front of the whole party. {b} said yes. The room exploded.",
      "{a} got down on one knee. {b} cried. Everyone clapped. The AI played a wedding march. Wrong one."
    ],
    fight: [
      "{a} and {b} started a fight at the party. Security was called.",
      "A fight broke out between {a} and {b}. The punch bowl did not survive."
    ]
  }
};
