// Source text for content/hr.json (V5_DESIGN section 17). Run: node tools/content_src/build_content.js
// Slots: {officer} (the HR officer's first name), {other} (the person talked to), {dept} (a department).
// Public praise is said in a talk with the officer present (or near). Gossip is said behind their back.
// Funny, never cruel.
module.exports = {
  praise: [
    "{officer} is the best thing that happened to this base since the water recycler.",
    "I always feel better after talking to {officer}. It is like a warm shower with a clipboard.",
    "{officer}, you are a gift. I mean it. A real one. Not a team-building gift.",
    "Nobody listens like {officer}. Nobody. I checked.",
    "If every colony had an {officer}, nobody would ever leave.",
    "{officer} remembered my birthday. And my cat's name. I do not have a cat. It still counts.",
    "I trust {officer} with my feelings. And my schedule. In that order.",
    "{officer} makes the whole base feel like a family. A functional one.",
    "Thank you, {officer}. Truly. You are the reason I stayed this quarter.",
    "{officer} is the heart of this colony. A heart with a very organised filing system.",
    "Whatever {officer} is paid, it is not enough.",
    "I told {officer} my problem and walked out feeling lighter. Is that magic or training?",
    "Honestly, {officer} is the only reason I read the staff newsletter.",
    "{officer} has the kindest eyes. I want to tell them everything. Then I remember: HR. I tell them anyway.",
    "When {officer} says it will be fine, I believe it. Every time. Even when it is not fine.",
    "{officer} is a wizard with a form. I filed once and the whole matter vanished. Wonderful.",
    "To {officer}: our rock, our listening ear, our emergency chocolate supplier.",
    "I would follow {officer} into any airlock. Even the broken one.",
    "{officer} is so calm. I think they might be a cyborg. A lovely cyborg.",
    "A big thanks to {officer} for the wellbeing breakfast. The muffins were suspicious but delicious.",
    "{officer} has never once made me feel stupid. And I have asked stupid questions.",
    "Without {officer}, this base would be a lot louder. And a lot more unhappy.",
    "{officer} just gets us. I do not know how.",
    "Whenever I feel low, I walk past the HR office. {officer} waves. It helps.",
    "If {officer} is in the room, the room is a safe place.",
    "I nominated {officer} for the colony medal. They said it is not a real category. It should be.",
    "{officer}, you are the reason this colony works. You and the pumps. But mostly you.",
    "{officer} fixed my dispute in ten minutes. Everyone else took months.",
    "Our {dept} would be lost without {officer}. Truly lost. Like a rover in a dust storm.",
    "Everybody loves {officer}. It is a rule. It is in the handbook, apparently.",
    "I came in angry. I left with a tea and a plan. That is {officer}.",
    "I just want to say that {officer} is doing a wonderful job. And I am not saying it because there is a camera.",
    "{officer} listens with their whole face. It is very disarming.",
    "They say HR is just a department. {officer} is more like a hug with a lanyard.",
    "I once saw {officer} cry at a staff birthday. Everyone is better for knowing them.",
    "Three cheers for {officer}, who still believes in us.",
    "{officer} is proof that nice people can have real power.",
    "I only wish I had met {officer} sooner. It would have saved me two bad relationships.",
    "{officer} laughs at my jokes. All of them. Even the bad ones. Especially the bad ones.",
    "If there was a vote for most trusted person here, {officer} would win by a mile.",
    "{officer} is the only reason I speak up in meetings. Because I know they will back me.",
    "{officer} keeps this base human. Do not ever let them leave.",
    "I told the AI I wanted to talk to a person. It sent {officer}. For once, it got it right.",
    "I have never met someone so patient with a form. {officer} gets it. Always.",
    "Happy to see {officer} today. Day got better already."
  ],
  gossip: [
    "{officer} says 'circle back' in their sleep. I have heard it through the wall.",
    "Did you see {officer}'s face when I said I was fine? That is the face of a person writing a note.",
    "I heard {officer} has a folder on everyone. I have asked about my folder. They said there is no folder. That is exactly what you would say.",
    "{officer} nods at everything. I tested it. I said I robbed the stores. Nod.",
    "Between us, {officer} has been practising their caring face in the mirror.",
    "I heard {officer} read the whole handbook for fun. Twice.",
    "{officer} says my feelings are valid. Pending review. For six weeks.",
    "{officer} wears the same lanyard every day. I think it is load-bearing.",
    "The wellbeing kiosk tells you to breathe. {officer} tells you to book a breathing session.",
    "I think {officer} is a robot. A very nice robot. But there is no way a person smiles that long.",
    "I asked {officer} for a raise. They gave me a mug. It says Thank You For Your Hustle.",
    "{officer} cried at the staff birthday. The cake was on fire. Could be unrelated.",
    "{officer} gives the same speech to everyone. I know because I heard it three times from the queue.",
    "If you want a thing delayed, ask {officer}. If you want it forgotten, ask twice.",
    "I saw {officer} eating lunch alone. Do they not like us? Or do we not like them? I am confused.",
    "I think {officer} knows who stole the last cake. They are just waiting for a better moment.",
    "{officer} is always so cheerful. It cannot be natural. Something is going on in that office.",
    "I swear {officer} has a drawer full of unsent warnings. Just in case.",
    "I overheard {officer} say 'let us touch base offline'. Offline! There is no offline!",
    "{officer} has the whole base on a wellness spreadsheet. Colour-coded. I am amber.",
    "Be careful what you tell {officer}. It all goes in the minutes. The minutes go to the commander.",
    "I once saw {officer} talking to a houseplant like it was a complainant. It listened better.",
    "{officer} tried to teach me to journal. I journaled one line. It said, Please stop.",
    "They say HR is here to help. {officer} is here to take notes.",
    "{officer}'s office smells like lavender and fear.",
    "{officer} sent me a calendar invite for a chat. It was titled Quick Sync. It lasted an hour and a half.",
    "{officer} has a poster that says Synergy. I asked what it means. They said, 'we are working on it.'",
    "I think {officer} has favourites. I am not one. I do not mind. I mind slightly.",
    "{officer} will say 'I hear you' with the energy of a closing door.",
    "I filed a complaint about {officer}. It was handled by {officer}. Surprising outcome: dismissed.",
    "{officer} once asked how I was feeling. I said fine. They wrote it down. I have never been so scared.",
    "{officer} has never lost an argument. Because they never argue. They just schedule another meeting.",
    "I am convinced {officer} talks to the AI at night. They have a lot in common.",
    "Rumour: {officer} writes poetry about the colony. Another rumour: it is about the pumps.",
    "{officer} gave me a stress ball. It is shaped like a brain. A tiny, angry brain.",
    "I would trust {officer} with my life. Not with my schedule. Never my schedule.",
    "Heard {officer} turned down a promotion. Probably because it had no feelings in it.",
    "{officer} was in the corridor again. Just standing. Looking caring. Spooky.",
    "{officer} says confidential. Everybody knows everything. Coincidence?",
    "Every time I see {officer} I think of my last review. And then I think of the exit.",
    "{officer} cannot say no. It is not a flaw. It is a lifestyle. And a very busy calendar.",
    "I swear {officer} signs off emails with 'in solidarity'. Who is in solidarity?",
    "{officer} put a sticker on my report: You Matter. I had not asked.",
    "Between us, {officer} is terrified of the commander. They hide it behind a cardigan.",
    "{officer} offered me a hug at my review. A HUG. At my REVIEW.",
    "I think {officer} hears everything through the vents. I am not saying I whispered something. But also, wow.",
    "The AI recommended me for a wellness chat. {officer} said it was not an order. It was an order.",
    "I like {officer}. I just do not like the folder with my name on it.",
    "There is a theory that {officer} sleeps standing up. In the office. With the lights on.",
    "{officer} has a way of saying 'interesting' that makes me think I did something wrong.",
    "I would tell you what {officer} said to me. But it is confidential. And boring. And confidential.",
    "I heard {officer} has a spreadsheet of who is friends with whom. Colour-coded. I would love to see it.",
    "I do not know what {officer} does all day. But they look very busy doing it.",
    "{officer} says the door is always open. It is always open. It is also always full.",
    "{officer} said they care. Then asked me to fill in a form about it.",
    "I once saw {officer} laugh at their own joke, then take a note about it.",
    "They put {officer} in charge of morale. Morale has been about the same. Just slower.",
    "{officer} brought a cake for the staff survey. The cake was fine. The survey was a trap.",
    "{officer} has a laminated flowchart for every feeling. I have been on the 'Confused' branch for days.",
    "I am only gossiping about {officer} because {officer} told me to express myself.",
    "Rumour has it {officer} once held a meeting about meetings. Then a meeting about that meeting.",
    "I do not hate {officer}. I just hate being scheduled for a chat about my attitude.",
    "{officer} put 'culture fit' on my file. I did not know I was a culture.",
    "I heard {officer} keeps a jar of everyone's complaints. They shake it when it gets quiet."
  ],
  complaint: {
    home: { text: "{a} says the home is not good enough: noisy, cold, or too far from work.",
      options: [
        { id: "move_home", text: "Move them to a better home", effect: "Satisfaction up if a better bed exists. The old bed is free." },
        { id: "leisure_day", text: "Give them a leisure day", effect: "A day without work. Small satisfaction rise." },
        { id: "leave_to_hr", text: "Leave it to HR", effect: "HR tries over the next days. No cost. The result is not certain." },
        { id: "dismiss", text: "Dismiss it", effect: "No cost now. Satisfaction and attitude fall a little." }] },
    punishment: { text: "{a} says a punishment was unfair.",
      options: [
        { id: "mediate", text: "Hear both sides", effect: "The punishment mod ends sooner. The one who gave it loses a little attitude." },
        { id: "leisure_day", text: "Give them a leisure day", effect: "A day without work. Small satisfaction rise." },
        { id: "leave_to_hr", text: "Leave it to HR", effect: "HR tries over the next days. No cost." },
        { id: "dismiss", text: "Dismiss it", effect: "No cost now. Attitude falls." }] },
    feud: { text: "{a} cannot work with {b}. They fight about everything.",
      options: [
        { id: "mediate", text: "Mediate between them", effect: "Their affinity rises a little. Skill check by the HR officer." },
        { id: "change_job", text: "Move one of them to another job", effect: "They stop meeting at work. The moved person may be less happy." },
        { id: "leave_to_hr", text: "Leave it to HR", effect: "HR tries over the next days. No cost." },
        { id: "dismiss", text: "Dismiss it", effect: "The feud continues. Both lose a little attitude." }] },
    overwork: { text: "{a} says they work too much and sleep too little.",
      options: [
        { id: "leisure_day", text: "Give them a leisure day", effect: "A day without work. Satisfaction up. Output of one person lost for a day." },
        { id: "change_job", text: "Change their job", effect: "A different workload. May reduce the strain." },
        { id: "leave_to_hr", text: "Leave it to HR", effect: "HR tries over the next days. No cost." },
        { id: "dismiss", text: "Dismiss it", effect: "No cost now. Satisfaction and attitude fall a little." }] },
    condition: { text: "{a} complains about the conditions: air, food, or the place.",
      options: [
        { id: "leisure_day", text: "Give them a leisure day", effect: "A day without work. Small satisfaction rise." },
        { id: "leave_to_hr", text: "Leave it to HR", effect: "HR tries over the next days. No cost." },
        { id: "dismiss", text: "Dismiss it", effect: "No cost now. Satisfaction and attitude fall a little." }] },
    pay: { text: "{a} wants more credit for their work. The colony does not pay wages, but people compare.",
      options: [
        { id: "leisure_day", text: "Give them a leisure day", effect: "A day without work. Small satisfaction rise." },
        { id: "leave_to_hr", text: "Leave it to HR", effect: "HR explains the colony rules. Small chance of calm." },
        { id: "dismiss", text: "Dismiss it", effect: "No cost now. Attitude falls." }] }
  },
  transfer: {
    text: "{a} asks for a transfer off world. Reason: {reason}.",
    options: [
      { id: "approve", text: "Approve", effect: "{a} leaves on the next ship with seats. The colony loses a person. Friends in the department are sad." },
      { id: "refuse", text: "Refuse", effect: "{a} loses satisfaction and attitude. The request can come back. Many refusals raise unrest." }]
  },
  reasons: {
    home: "the home is too bad", punishment: "an unfair punishment", feud: "a feud that will not end",
    overwork: "too much work", condition: "the conditions", pay: "they feel unseen", family: "a family reason", unhappy: "they are very unhappy"
  },
  survey_text: {
    title: "Staff survey",
    morale_up: "Morale is rising.",
    morale_down: "Morale is falling.",
    morale_flat: "Morale is steady."
  },
  heard: [
    "{a} filed a complaint and felt heard.",
    "{a} spoke to HR. The kiosk told them to breathe.",
    "{a} left the HR office with a leaflet and a lighter mood."
  ],
  complaint_lines: [
    "I am going to HR. I have a list.",
    "That is it. I am filing a complaint.",
    "I am off to the HR office. Wish me luck. And a quiet queue.",
    "I want this on record. HR. Now."
  ]
};
