// Builds content/names.json: the first and last names of the people the sim makes (sim.next_name).
//   node tools/content_src/names_data.js
// 180+ first names and 180+ last names from many cultures, so that every full name in a colony is its own.
// Children take a parent's last name. No numbers are ever added to a name.
const fs = require("fs");
const path = require("path");

const first = `Aaliyah Abel Adaeze Adrian Agnes Aiko Alana Alder Aleksi Alma Amara Amir Anders Anika Anselm Aroha Arvid Astrid
Ayaan Ayla Bao Beatriz Bela Benedikt Bilal Birgit Bryn Caio Camille Carlos Cassia Cato Cedric Chiara Chidi Cleo Cora
Corin Dalia Damir Dara Darius Delphine Dev Dilnoza Dmitra Dorian Eero Efua Eilidh Elio Elke Elodie Emre Enzo Esther
Eun Farid Fenna Fiona Florin Gabriel Gaia Gareth Gemma Gideon Greta Gunnar Habib Hadiza Halima Hamid Hanne Haruto Hedda
Hugo Ibrahim Ilse Imani Ingrid Ioana Irina Isaac Isla Ivo Jabari Jana Jasper Javier Jin Joaquin Johan Jorun Kalani Kamal
Karina Kasper Katya Kenji Kiona Klara Kwame Laila Lars Leandro Leilani Leo Liesel Linnea Livia Luca Lucia Lukas Mabel
Magnus Maia Makena Malik Mariam Marit Mateo Maya Meera Mehmet Mireille Miro Mona Nabil Naia Nanami Nils Nina Nkosi Noa
Odalys Olaf Olga Omar Oriel Oscar Otto Paloma Pavel Pilar Priya Quentin Rafaela Ragnar Rana Rashid Reiko Remy Rhea Rinat
Rowan Rui Saba Samir Sanna Sefa Selma Sergio Siena Signe Silvio Soraya Stefan Sunniva Tamsin Tariq Tavita Thea Theo
Timo Tove Tuan Ulla Umar Valentina Vera Vidar Wanjiru Willem Xavier Xia Yannick Yasmin Yuki Yusuf Zane Zainab Zora`
  .split(/\s+/).filter(Boolean);

const last = `Abara Abbasi Acheampong Adair Aguirre Ahlberg Akintola Alcott Amundsen Andrade Aranda Arvidsson Asante Aydin Baptiste
Barros Bekele Bergstrom Bianchi Blackwood Boateng Borges Brandao Bremer Caldwell Calloway Carvalho Castellan Cavalli
Chaudhry Chavez Chen Cisneros Colby Costa Dahl Dalgaard Danjuma Delacroix Demir Dlamini Donati Duarte Dunmore Echeverria
Ekwueme Eliassen Engstrom Estrada Fairweather Falk Farahani Ferrante Fitzroy Fofanah Fontana Forsberg Gallagher Garnier
Gebreyes Gholami Giordano Goncalves Grayson Gustavsen Haddad Hakimi Halloran Hartmann Hasegawa Hendry Hoang Holloway
Ibarra Idowu Iwasaki Jankowski Jensen Jovanovic Kaczmarek Kagame Kamara Karlsen Kasprzak Kawabata Keller Kilbride Kimura
Kowalczyk Krause Lacerda Lamprecht Landry Larkin Lazarev Lemaire Lindgren Lombardi Lovell Macedo Madsen Maguire Mahlangu
Makinen Maldonado Mansouri Marchand Mazur Mbatha Medina Meyer Mikkelsen Molina Montrose Mukherjee Nakamura Nascimento
Ndlovu Nielsen Nikolaidis Novak Nyberg Obuya Ochoa Okonkwo Olsen Oyelaran Pacheco Palmer Paredes Pellegrini Petrenko
Pettersen Quispe Radcliffe Rahimi Ramires Rasmussen Reyes Rinaldi Rostami Rousseau Saavedra Sakamoto Salazar Santoro
Schaefer Sekou Shevchenko Silvera Sorensen Stoica Suzuki Tanaka Teixeira Thorsen Tkachenko Torres Ueda Valdez Varela
Vasquez Verhoeven Vukovic Wachira Waller Whitlock Wojcik Yamamoto Yilmaz Zamora Zhao Zielinski Zuberi`
  .split(/\s+/).filter(Boolean);

function check(list, what) {
  const seen = new Set();
  for (const n of list) {
    if (seen.has(n)) throw new Error("duplicate " + what + ": " + n);
    seen.add(n);
  }
  if (list.length < 150) throw new Error(what + " has only " + list.length);
}
check(first, "first name");
check(last, "last name");
const out = {
  _note: "People's names (sim.next_name). Generated by tools/content_src/names_data.js. No numbers are added to a name.",
  first: first,
  last: last,
};
fs.writeFileSync(path.join(__dirname, "..", "..", "content", "names.json"), JSON.stringify(out, null, 2) + "\n");
console.log("first", first.length, "last", last.length);
